// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_5th_victory = "CgkI5_W8gYcCEAIQBg"; // <GPGSID>
        public const string achievement_clear_master = "CgkI5_W8gYcCEAIQAQ"; // <GPGSID>
        public const string leaderboard_maximum_coins = "CgkI5_W8gYcCEAIQBw"; // <GPGSID>
        public const string achievement_3rd_vicotry = "CgkI5_W8gYcCEAIQBA"; // <GPGSID>
        public const string achievement_2nd_victory = "CgkI5_W8gYcCEAIQAw"; // <GPGSID>
        public const string achievement_1st_victory = "CgkI5_W8gYcCEAIQAA"; // <GPGSID>
        public const string achievement_billiard_mania_master_victory = "CgkI5_W8gYcCEAIQAg"; // <GPGSID>
        public const string achievement_4th_victory = "CgkI5_W8gYcCEAIQBQ"; // <GPGSID>

}

